// ── Report shaping ───────────────────────────────────────────
// Grades per dimension, severity ordering, and the markdown export.
// Pure module: no DOM, runs unchanged under Node for the tests.

import { RULES } from './rules.js';

export const DIMS = [
  { id: 'router', label: 'Router' },
  { id: 'body', label: 'Body' },
  { id: 'files', label: 'Files' },
];

export const SEV_LABEL = { blocker: 'Blocker', warning: 'Warning', nit: 'Nit' };

/** A no findings, B nits only, C any warning, D any blocker. */
export function gradeDim(findings, dim) {
  const list = findings.filter((f) => f.dim === dim);
  if (list.some((f) => f.severity === 'blocker')) return 'D';
  if (list.some((f) => f.severity === 'warning')) return 'C';
  if (list.length) return 'B';
  return 'A';
}

export function grades(analysis) {
  const out = {};
  for (const d of DIMS) out[d.id] = gradeDim(analysis.findings, d.id);
  return out;
}

export function counts(analysis) {
  const out = { blocker: 0, warning: 0, nit: 0 };
  for (const f of analysis.findings) out[f.severity]++;
  return out;
}

export function verdict(analysis) {
  const c = counts(analysis);
  if (c.blocker) return 'Not ready to ship: fix the blockers first.';
  if (c.warning) return 'Shippable once the warnings get answers.';
  if (c.nit) return 'Ready, with nits worth one pass.';
  return 'Clean. Nothing to fix before it ships.';
}

export function bySeverity(analysis) {
  const groups = { blocker: [], warning: [], nit: [] };
  for (const f of analysis.findings) groups[f.severity].push(f);
  return groups;
}

/** Compact summary persisted to localStorage between sessions. */
export function summarize(analysis) {
  return {
    name: analysis.name || analysis.folderName || 'unnamed skill',
    source: analysis.source,
    at: new Date().toISOString(),
    grades: grades(analysis),
    counts: counts(analysis),
  };
}

/** The whole report as markdown, for copy or download. */
export function toMarkdown(analysis) {
  const g = grades(analysis);
  const c = counts(analysis);
  const lines = [];
  lines.push(`# Scalpel report: ${analysis.name || analysis.folderName || 'unnamed skill'}`);
  lines.push('');
  lines.push(`- Source: ${analysis.source === 'paste' ? 'pasted SKILL.md' : `zip (folder ${analysis.folderName || 'at root'})`}`);
  lines.push(`- Grades: Router ${g.router} / Body ${g.body} / Files ${g.files}`);
  lines.push(`- Findings: ${c.blocker} blockers, ${c.warning} warnings, ${c.nit} nits`);
  lines.push(`- Verdict: ${verdict(analysis)}`);
  const groups = bySeverity(analysis);
  for (const sev of ['blocker', 'warning', 'nit']) {
    if (!groups[sev].length) continue;
    lines.push('');
    lines.push(`## ${SEV_LABEL[sev]}s`);
    for (const f of groups[sev]) {
      lines.push('');
      lines.push(`### ${f.title}`);
      lines.push(f.detail);
      for (const ev of f.evidence) lines.push(`- ${ev}`);
      lines.push(`Rule: ${RULES[f.id].source}`);
    }
  }
  if (analysis.notes.length) {
    lines.push('', '## Notes');
    for (const n of analysis.notes) lines.push(`- ${n}`);
  }
  if (analysis.skipped.length) {
    lines.push('', '## Skipped checks');
    for (const s of analysis.skipped) lines.push(`- ${s.title}: ${s.why}`);
  }
  lines.push('', 'Generated by Scalpel (scalpel.neorgon.com); rules trace to the fleet skill-authoring guide.');
  return lines.join('\n');
}
